"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Check, X, RefreshCw, Edit3, Calendar, MoreHorizontal, ChevronLeft, ChevronRight, Image as ImageIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export function ContentApproval() {
  const [selectedPostId, setSelectedPostId] = useState<string | null>(null);
  const [drafts, setDrafts] = useState<any[]>([]);
  const [editMode, setEditMode] = useState(false);
  const [content, setContent] = useState("");

  // Fetch Drafts
  const fetchDrafts = () => {
    fetch('http://localhost:4000/api/v1/automation/posts?user_id=test-user-123')
      .then(res => res.json())
      .then(data => {
         setDrafts(Array.isArray(data) ? data : []);
         if (data.length > 0 && !selectedPostId) {
            setSelectedPostId(data[0].id);
            setContent(data[0].content);
         }
      })
      .catch(err => {
        console.error("Fetch error:", err);
        toast.error("Could not fetch drafts", { description: "Is the backend server running?" });
      });
  };

  useEffect(() => {
     fetchDrafts();
  }, []);

  useEffect(() => {
     if (selectedPostId) {
        const post = drafts.find(d => d.id === selectedPostId);
        if (post) setContent(post.content);
     }
  }, [selectedPostId, drafts]);

  const activePost = drafts.find(d => d.id === selectedPostId);


  const handleApprove = async () => {
     if (!activePost) return;
     toast.promise(
         fetch('http://localhost:4000/api/v1/automation/trigger-post', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ post_id: activePost.id, user_id: activePost.user_id })
         }).then(() => fetchDrafts()),
         {
             loading: 'Publishing to LinkedIn...',
             success: 'Post published successfully!',
             error: 'Failed to publish post'
         }
     );
  };

  return (
    <div className="grid lg:grid-cols-12 gap-6 h-[calc(100vh-220px)] animate-in fade-in slide-in-from-bottom-4 duration-500">
       
       {/* Left: Queue List */}
       <div className="lg:col-span-4 flex flex-col gap-4 overflow-y-auto pr-2">
          {drafts.length === 0 && (
             <div className="p-8 text-center text-muted-foreground border-2 border-dashed rounded-xl">
                No drafts found. <br /> Check the Trends tab to generate some.
             </div>
          )}
          {drafts.map(draft => (
             <div 
               key={draft.id}
               onClick={() => setSelectedPostId(draft.id)}
               className={cn(
                  "p-4 rounded-xl border cursor-pointer transition-all duration-200 group relative",
                  selectedPostId === draft.id 
                    ? "bg-card border-primary ring-1 ring-primary/20 shadow-md" 
                    : "bg-card/50 border-border hover:border-primary/50 hover:bg-secondary/20"
               )}
             >
                <div className="flex justify-between items-start mb-2">
                   <h4 className={cn("font-semibold text-sm line-clamp-1", selectedPostId === draft.id ? "text-primary" : "text-foreground")}>
                      {draft.content.substring(0, 30)}...
                   </h4>
                   <StatusBadge status={draft.status} />
                </div>
                <p className="text-xs text-muted-foreground line-clamp-2 mb-3 leading-relaxed">
                   {draft.content}
                </p>
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                   <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> {new Date(draft.created_at).toLocaleDateString()}</span>
                </div>
             </div>
          ))}
       </div>

       {/* Right: Editor / Preview */}
       {activePost ? (
       <Card className="lg:col-span-8 flex flex-col border-border shadow-sm overflow-hidden h-full">
          <div className="border-b px-6 py-4 flex items-center justify-between bg-card">
              <div className="flex items-center gap-3">
                 <div className="h-2 w-2 rounded-full bg-amber-500 animate-pulse" />
                 <div>
                    <h3 className="font-bold text-sm">Reviewing Draft</h3>
                    <p className="text-xs text-muted-foreground">Generated by Agent • {content.length} chars</p>
                 </div>
              </div>
              <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={() => setEditMode(!editMode)}>
                     <Edit3 className="h-4 w-4 mr-2" /> {editMode ? "Preview" : "Edit"}
                  </Button>
              </div>
          </div>
          
          <div className="flex-1 overflow-y-auto bg-secondary/5 p-6 md:p-10">
              <div className="max-w-2xl mx-auto bg-card border shadow-sm rounded-xl overflow-hidden min-h-[400px]">
                 {/* LinkedIn Mock Header */}
                 <div className="p-4 border-b flex gap-3">
                    <div className="h-10 w-10 bg-primary/10 rounded-full flex items-center justify-center font-bold text-primary">KA</div>
                    <div>
                        <div className="font-semibold text-sm">Krishil Agrawal</div>
                        <div className="text-xs text-muted-foreground">Building AI Canvas • Now • <span className="opacity-60">🌐</span></div>
                    </div>
                 </div>
                 
                 {/* Post Content */}
                 <div className="p-4 md:p-6 text-sm md:text-base leading-relaxed whitespace-pre-wrap font-sans text-foreground/90">
                    {editMode ? (
                        <textarea 
                           className="w-full h-[300px] bg-transparent resize-none focus:outline-none" 
                           value={content}
                           onChange={(e) => setContent(e.target.value)}
                        />
                    ) : (
                        content
                    )}
                    
                    {/* Mock Media Placeholder if needed */}
                 </div>

                 {/* Mock Footer Actions */}
                 <div className="border-t bg-secondary/5 px-4 py-3 flex justify-between text-muted-foreground">
                    <div className="flex gap-4 text-xs font-medium">
                       <span>Like</span>
                       <span>Comment</span>
                       <span>Repost</span>
                       <span>Send</span>
                    </div>
                 </div>
              </div>
          </div>

          <div className="border-t p-4 bg-card flex justify-between gap-4">
             <Button variant="ghost" className="text-muted-foreground hover:text-foreground">
                <RefreshCw className="mr-2 h-4 w-4" /> Regenerate
             </Button>
             <div className="flex gap-3">
                <Button variant="outline" className="border-destructive/30 text-destructive hover:bg-destructive/10 hover:text-destructive">
                   <X className="mr-2 h-4 w-4" /> Reject
                </Button>
                {activePost.status === 'published' ? (
                   <Button disabled className="bg-secondary text-muted-foreground">
                      <Check className="mr-2 h-4 w-4" /> Published
                   </Button>
                ) : (
                   <Button onClick={handleApprove} className="bg-green-600 hover:bg-green-700 text-white shadow-lg shadow-green-900/20">
                      <Check className="mr-2 h-4 w-4" /> Approve & Schedule
                   </Button>
                )}
             </div>
          </div>
       </Card>
       ) : (
          <div className="lg:col-span-8 flex items-center justify-center h-full border rounded-xl border-dashed text-muted-foreground">
             Select a draft to review
          </div>
       )}
    </div>
  )
}

function StatusBadge({ status }: { status: string }) {
   if (status === "approved") {
      return <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-green-500/10 text-green-600 border border-green-500/20">Approved</span>
   }
   if (status === "published") {
      return <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-600 border border-blue-500/20">Published</span>
   }
   if (status === "rejected") {
      return <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-red-500/10 text-red-600 border border-red-500/20">Rejected</span>
   }
   return <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600 border border-amber-500/20">Review</span>
}


